services:
  - type: web
    name: ytsummary-api
    env: python
    plan: free
    region: oregon
    buildCommand: ./ytsummary-api/build.sh
    startCommand: gunicorn main:app -k uvicorn.workers.UvicornWorker --chdir ytsummary-api
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: JWT_SECRET_KEY
        sync: false
      - key: JWT_EXPIRATION
        sync: false
      - key: COOKIE_B64
        sync: false
